### ISSUE TITLE
Dynamic theme in Shiny does not work

### ISSUE THREAD

**Issue by barnesparker** [federiva/highlighter#8]
``` r
library(shiny)
library(highlighter)
shinyApp(
  ui = fluidPage(
    selectInput(
      "reactive_theme",
      "Theme",
      get_available_themes()
    ),
    highlighterOutput("code")
  ),
  server = function(input, output) {
    output$code <- renderHighlighter({
      highlighter('print("hello world")', theme = input$reactive_theme)
    })
  }
)
```

  <sup>Created on 2024-02-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by federiva** [comment]
Hi @barnesparker!
Thanks for using this package!

Short answer is that right now it is not possible to do what you're doing there BUT it is possible.

The reason of why it is not possible is that the htmldependency being rendered has the same name and therefore is not being rendered more than once. We could easily solve this, but there are a few drawbacks.

1. Themes in Prism are using the same class names and all the classes from Theme A are not necessarily present in Theme B. This causes that when you're switching themes like in your example you'll end up piling up these classes that are defined in Theme A but not in Theme X (See screenshot)![highlighter](https://github.com/federiva/highlighter/assets/25372718/4b133854-85cc-4ede-b450-f4362c98aa5d)


We could also solve the issue described above by explicitly removing the stylesheets that are not needed when updating the theme but we will have now a new problem

2. The highlighted code (htmlwidget) widgets are not isolated from one another. Since that the class names from theme to theme are not different, and we are loading stylesheets if you change the theme of one widget all the other widgets will be changed as well.

All of these issues could be avoided if we render the htmlwidget within a web component with isolated styles, I can see some performance-related drawbacks to this approach, but probably they'll not be as bad considering that the library + the styles are not that big. 

So **the question is**. If you cannot use multiple themes within the same instance of a shiny app, are you losing something in terms of UI/UX?

If so, I'll consider implementing this as a web component to allow multiple themes to be rendered within the same session.

**Comment by barnesparker** [comment]
Thanks for the thoughtful response and willingness to help @federiva! Let me explain my particular use case and hopefully that will illuminate the path forward.

In my shiny app I am leveraging the new [`bslib::input_dark_mode()`](https://rstudio.github.io/bslib/reference/input_dark_mode.html) function. I want to switch the code highlight theme based on what mode the app is in ("light" or "dark"). Happy to provide a reprex demonstrating this if it would help.

> 2. The highlighted code (htmlwidget) widgets are not isolated from one another. Since that the class names from theme to theme are not different, and we are loading stylesheets if you change the theme of one widget all the other widgets will be changed as well.

If I'm understanding correctly, this would actually be desirable behavior in my case. If the app is in dark mode, I want all highlighter widgets to switch to the same dark theme, and vice versa.

> So **the question is**. If you cannot use multiple themes within the same instance of a shiny app, are you losing something in terms of UI/UX?

Yes, it would be ideal to have multiple (2) themes in my app. However, I don't think distinct web components is necessary in my case for the reasons already stated.

> We could also solve the issue described above by explicitly removing the stylesheets that are not needed when updating the theme

Could you provide a reprex showing this? Or would it be a change in the package?


Thanks again for your response and for this package! Let me know if there's anything I can help with.

**Comment by federiva** [comment]
Great! I think that I understand your issue better now.

> Could you provide a reprex showing this? Or would it be a change in the package?

I think that the package should do it.
Would you like to test [this branch](https://github.com/federiva/highlighter/tree/feat-theme-switch)? To see if now is covering your use case?
You can try installing it via `remotes::install_github("federiva/highlighter", ref = "feat-theme-switch")`

Once you have the package installed from this branch you can also try running the example shiny app
`shiny::shinyAppFile(system.file("examples/shiny_app.R", package = "highlighter"))`


I'm not 100% happy with this implementation but I guess that it's better than the previous step, if you're OK with this implementation then I'll merge this changes to dev and prepare for releasing the changes to CRAN in the next few weeks 🤞

**Comment by barnesparker** [comment]
Looks like that solution worked! The only issue now is that when I switch themes, there's kind of an ugly transition state that flashes on the screen. It's so quick that even a gif doesn't capture it. But if you select `help/AnIndex` as the input file in the example shiny app, you'll see what I mean.

To be clear, this is not a huge issue for me. I just wanted to point it out and see if it was an easy fix. If not, I wouldn't worry too much about it!

**Comment by federiva** [comment]
I wasn't able to reproduce :disappointed: but anyways I changed the way in which I was clearing old CSS files and I think that now should be different. Would you give it a try now please?

**Comment by barnesparker** [comment]
That fixed it!
